### ISSUE TITLE
Total time: Different formats

### ISSUE THREAD

**Issue by Ronef** [NekitCorp/better-workflowy#23]
The total time is now formatted as `d h m`.

But for me it is more important to see how many _hours_ have been spent. Therefore, I suggest adding at least one more format `h m`:

![image](https://user-images.githubusercontent.com/1333424/233805446-3e0a69b6-7c59-4208-b835-db5f6d96aa65.png)

**Comment by NekitCorp** [comment]
Hello, I will try to add new formats as soon as possible.

**Comment by NekitCorp** [comment]
Published a new [v2.0.0](https://chrome.google.com/webstore/detail/better-workflowy/kmkdngajnjecnkdpiddmkongflkcojlg) version of the extension.

<img width="606" alt="image" src="https://user-images.githubusercontent.com/15874982/235608972-930b7bfc-c6d0-47ee-badb-00039e307c14.png">

Now using these settings you can achieve the desired result.

**Comment by Ronef** [comment]
Спасибо огромное! 🔥
