### ISSUE TITLE
Incorrect time calculation

### ISSUE THREAD

**Issue by Ronef** [NekitCorp/better-workflowy#33]
I see 32h 43m in extension but in fact is ≈13h.

![image](https://github.com/NekitCorp/better-workflowy/assets/1333424/f82fbb6c-23af-46dc-8517-a1033dbe1a42)

I'm a web developer too, so i can help you with tests. Please contact me via Telegram: [t.me/Ronef](https://t.me/Ronef).

**Comment by NekitCorp** [comment]
This seems to be a problem with the extension not taking into account expanding and collapsing items. Please try to reproduce the problem in the new version of the extension `2.2.1` (it is still in the process of release and may not be available right now).

> I'm a web developer too, so i can help you with tests.

You can freely send any improvements or tests (unit – vitest, e2e – playwright) as a pull request 😉

**Comment by Ronef** [comment]
![image](https://github.com/NekitCorp/better-workflowy/assets/1333424/8bb99e96-0bf5-40c5-874e-ce0d3ca122be)

**Comment by NekitCorp** [comment]
<img width="803" alt="image" src="https://github.com/NekitCorp/better-workflowy/assets/15874982/9062e6f6-dc65-4483-a3f7-13cd3ebcc975">

🤔 I don’t quite understand all the features of `workflowy`, but could the `#use-template:...` include other tags over time?  Could you find other elements with attribute `data-val="#14m"` in the browser's devtools that add time to the total?

**Comment by Ronef** [comment]
But i find a lot of hidden elements:
![image](https://github.com/NekitCorp/better-workflowy/assets/1333424/e238e06d-5275-4e44-affc-450ad72e6815)

**Comment by Ronef** [comment]
It is hidden sidebar navigation items:

![image](https://github.com/NekitCorp/better-workflowy/assets/1333424/a77cb8bf-b51a-49bc-bb1f-f11a3dc6a96b)

Just use items only from inside `.pageContainer`, not from `.leftBar`, `.header`, etc.

**Comment by NekitCorp** [comment]
Thanks for your help in finding the problem! 🙏 
Please try to look at the new `2.2.2` version (when it is released).

**Comment by Ronef** [comment]
You're welcome! 🙏 

I've updated the extension and everything is fine now. Thanks for your work and such a quick response! 🔥
